version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokemon_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: